axis_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: axismotor
    joint_speed: 0.5
    motor:
        id: 5
        init: 2047
        min: 1023
        max: 2559